### ISSUE TITLE
Add DirectX?

### ISSUE THREAD

**Issue by evilrat666** [dlang-community/discussions#18]
After my announcement that I discontinue working on directx bindings[1][2] I got suggestion[3] from Petar Kirov aka ZombineDev to contact your organisation, so you can take the role of maintaining the bindings. 

What is required for approval, how do I make transfer or what is necessary?

[1] https://github.com/evilrat666/directx-d
[2] http://code.dlang.org/packages/directx-d
[3] https://forum.dlang.org/post/mkcikaknamgfcmfucnga@forum.dlang.org

**Comment by BBasile** [comment]
I see [0 dependent projects](https://libraries.io/dub/directx-d). Are these bindings that popular ? 

That being said if Zombine agrees to make the maintenance required I see no problem and the invite can be sent to evilrat. This is really required because this kind of stuff don't interest me and i think that wilzback either since he's on linux too (i've read recently). One of our rule is to have a somone who can work on the stuff. We should avoid the scenario where 1/ something is dropped to the community 2/ nobody cares 3/ we'are accused of not maintaining it.

**Comment by BBasile** [comment]
Also this looks like something for deimos or DerelictOrg.

**Comment by BBasile** [comment]
on IRC i've also talked to this to @rikkimax doesn't care much either, apparently because of the bindings made for WinRT-d, which are auto-generated (https://github.com/WebFreak001/dwinrt/tree/master/directx)

**Comment by evilrat666** [comment]
I have no idea on how much it is popular (if at all).
That WinRT stuff is very sparse. And that's was the one of the reasons why I started working on bindings back then. 

Ok, got the point. I'll wait a bit for Zombine's decision though.

**Comment by wilzbach** [comment]
> That being said if Zombine agrees to make the maintenance required I see no problem and the invite can be sent to evilrat. 

Same here, I am not a Windows user, but as long as the repo has someone to look over and approve PRs, I am absolutely fine - in fact that's the main purpose of dlang-community.

> Also this looks like something for deimos or DerelictOrg.

I'm not entirely sure, but I think @mdparker has recently stated that "new" bindings should simply be put on DUB as DerelictOrg heavily predates DUB's lifetime.
@p0nce, @mdparker: what's your stand on this?

> don't interest me and i think that wilzbach either since he's on linux too (i've read recently)

Yup.

**Comment by BBasile** [comment]
From IRC, a couple of min. ago:

>[13:42] <B4S1L3> WebFreak, how would it be hard to maintain an automated version of DX bindings ? Is that just about running a tool and there they are.
[13:43] <WebFreak> yes, you just run the generator on the Windows SDK folder

I'm afraid that these hand written bindings are waste of time. Webfreak generates them with a tool. Right now he did just  dx11 but it seems that all versions would be possible, as long as the IDL exist.

**Comment by mdparker** [comment]
@wilzbach Yeah, not interested in putting them in DerelictOrg. It's not because dub came later (DerelictOrg exists because of dub, actually), but because among the maintainers of the packages I've added that weren't mine, Guiilaume is the only one who stayed on. I'm now saddled with maintaining the rest. And now that dub's position is cemented, there's really no need to pull other people's packages in.

**Comment by evilrat666** [comment]
Thanks everyone. I'll try something else then, but since there is IDL generator I'm not sure this is actually needed anymore. That's all.
