### ISSUE TITLE
WTF is this Dich library ?

### ISSUE THREAD

**Issue by BBasile** [dlang-community/discussions#20]
https://github.com/dlang-community/dich

@kozhevnikov-peter, i've already sent you an email ? Did you mean to push this elsewhere ? Does anyone else is aware of this ? @wilzbach ?

1- this organization is made for public projects of interest (this implies that the projects exist for a while).
2- Dich is even not on code.dlang.org.
3- previous additions were always discussed.

I think that other members deserve an explanation.

**Comment by wilzbach** [comment]
> Did you mean to push this elsewhere ? Does anyone else is aware of this ?

Nope. I also think that dlang-community should only be used to push work that has been __proven to be useful for the community__ and not personal projects. If they turn out to be successful, things are, of course, different.
There's also the exception that if a new project that will immediately benefit the community - e.g. like DUB2 would be started, dlang-community could be a good host, but in any case such this would require a discussion __before__.

**Comment by wilzbach** [comment]
For convenience a link: https://github.com/dlang-community/dich

**Comment by BBasile** [comment]
@kozhevnikov-peter, i'm going to delete this repository at 7PM, Paris time so in 9 hours and a half, unless we receive explanations from you part (or your coworker).

Thanks !

**Comment by kozhevnikov-peter** [comment]
Hello, community!
The problem started with the use vibe.d by us. We could not get the code coverage. This is the build options for test application: `"buildOptions": ["unittests", "coverage"]`. Output log:
![2017-07-17 11-34-34](https://user-images.githubusercontent.com/6961601/28260529-253edd18-6ae4-11e7-9bf9-9d50c205fdaf.png)
To solve the problem, we used the compilation flag `--combined` (as @s-ludwig recommended in [issue 767](https://github.com/rejectedsoftware/vibe.d/issues/767)). To implement one of our own projects we needed DI (Dependency injection). The most relevant is the library of endovena. But after adding all the dependencies and running the tests, we get infinity loop:
![2017-07-17 11-44-25](https://user-images.githubusercontent.com/6961601/28260795-5f8ae6b4-6ae5-11e7-941b-db1e2d14aecb.png)
The problem is associated with the use of `unit_threaded` in the `endovena` library. We decided to implement our own library for DI.
We planned to use CI for:
- coverage (coveralls service)
- tests (bdd style)
- dscanner (style, syntax)
- docs (ddox deploy to github pages as [DICH](https://dlang-community.github.io/dich/))

We also planned to implement a demonstration repository structure that will help the rest of the developers to make a documented and tested design project. Most of the projects in D have almost no documentation, are poorly tested, code coverage and code quality are not tracked, and sometimes there are no worthy code examples. Such situations as with endovena arise repeatedly. Libraries are no longer supported. Often their development stops half way. We wanted to create a library that could be immediately supported by the community, meet all the requirements of corporate projects regarding the quality of the code. All of this makes it difficult for commercial development in this language. We did not want to offend anyone by this action. We wanted to give impetus to the development of the language community D.

We agree to **remove the repository within the next hour**. We apologize for the inconsistent creation of the repository.

**Comment by BBasile** [comment]
Okay, but do this elsewhere. The deletion threat is still there.

**Comment by kozhevnikov-peter** [comment]
@BBasile Threat of removing what? The repository has already been moved. We do not intend to make similar attempts to develop a community of D language.

**Comment by BBasile** [comment]
okay. Thanks for the quick and adequate reaction.

**Comment by wilzbach** [comment]
> The problem started with the use vibe.d by us. We could not get the code coverage.

-> https://issues.dlang.org/show_bug.cgi?id=13742

> We wanted to create a library that could be immediately supported by the community, meet all the requirements of corporate projects regarding the quality of the code. All of this makes it difficult for commercial development in this language. We did not want to offend anyone by this action. We wanted to give impetus to the development of the language community D.

I think I need to de-escalate this a bit. @kozhevnikov-peter you simply should have opened an issue to discuss this before. We all didn't know about dich, your goals and were just confused.
If you are actively developing the library, that's great and then there's no need for `dlang-community`. On the contrary, it's advertisement for your company!
If you ever run out of time to maintain the library and it's popular in the D community, please don't hesitate to talk with us. We are very open to adopt orphaned, key components of the D infrastructure ;-)

**Comment by BBasile** [comment]
> I think I need to de-escalate this a bit.

There was nothing personal, although me being a bit tough could create tensions. The only important point in this little event is that the addition was no discussed. We should add this to the rules. Don't create new repos without consulting the other members.

**Comment by wilzbach** [comment]
> There was nothing personal, although me being a bit tough could create tensions. The only important point in this little event is that the addition was no discussed. 

Yeah, but I was a bit sad when I read:

> We do not intend to make similar attempts to develop a community of D language.

@kozhevnikov-peter I hope that this incident didn't break your love to D ;-)

>  We should add this to the rules. Don't create new repos without consulting the other members.

https://github.com/dlang-community/discussions/pull/21

**Comment by zhiganov-andrew** [comment]
Hello everyone!
I work in LLC Cereis as a CTO. As you know with @kozhevnikov-peter. 

> Yeah, but I was a bit sad when I read:
> > We do not intend to make similar attempts to develop a community of D language.

At that moment all the developers in our company use D language in an active way. We're not gonna change that fact. Dlang has quite good prospects to become a really popular language. Nowadays a lot of people in IT sphere don't realize its positive sides. And only d community can change the situation by creating and supporting easyToUse various libraries and instruments.
As @BBasile mentioned there wasn't such a rule about adding a new repo only after discussions. But honestly I was confused by his reaction a little bit. Despite there was the bad start of our discussion I'm glad that the situation has been resolved now.
According to our job (we've got some own projects in security systems and remote data collection systems) we're gonna develop some new instruments or libs for Dlang as public projects on Github. If they we're used by dlang users, we're ready to integrate them into dlang community
