### ISSUE TITLE
Stop testing with the beta and the nightly compiler versions

### ISSUE THREAD

**Issue by BBasile** [dlang-community/discussions#29]
It makes more sense on the side of the compilers (e.g DMD Jenkins test) but not on the side of the end product. After all, a failure may indicate a problem with the pre-release versions of the compilers, not the product made with the compiler.

**Comment by wilzbach** [comment]
For reference, this issue was motivated by https://github.com/dlang-community/DCD/pull/423.  However, in this case the failure were spurious, i.e. it's the testsuite's fault - not a regression in the compiler. You were just unlucky that it happened for ldc-beta.
IIRC the only recent problem we had with testing nightly and beta was with ldc-beta on Windows recently, but that's due to them changing the release archives and will happen as part of 1.7.0 anyways.

Reasons to keep the tests:
- Not all projects here are tested by the compiler
- There's no project tester for LDC
- There's no project tester for Windows
- If it's not us who is testing the betas, who else?
- We haven't had much issues over the last months
- We catched regressions in the past that weren't detected by the Project tester

**Comment by BBasile** [comment]
I understand, but i have the feeling that you blend your role at dlang and here. My point of view is simply _"it's not our job"_.

**Comment by skl131313** [comment]
I made this argument when they were first added, I don't like seeing the build failing cause of bugs in a beta compiler. It makes some feature of CI kind of useless. Making a separate repo or something that runs the tests for the experimental versions of the compilers would be more ideal. It can be automated to some extent, and if the build fails it could ping someone over at DMD/LDC to bring it to their attention for them to fix. That way it won't break CI features in the development repos of these projects.

**Comment by BBasile** [comment]
Yeah or use another CI for the betas and nightly, not marked as "required".

**Comment by wilzbach** [comment]
FYI:

I went with this PR https://github.com/dlang/ci/pull/102 (we added more projects to the Jenkins project tester).
So feel free to remove `dmd-nightly` the next time you run into issues.

**Comment by BBasile** [comment]
Understood, thank you.
