### ISSUE TITLE
Moving std.data.json to dlang-community

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/discussions#37]
See e.g. https://github.com/s-ludwig/std_data_json/pull/38#issuecomment-412898009

If anyone objects, he should speak now.

**Comment by Geod24** [comment]
I think that would make a lot of sense.
JSON is a widely popular format and not having such a good module in the standard library hurts a lot.

What is the deadline for this decision ?

Side note:
One thing that std_data_json (and std.json) are lacking is the ability to go from/to a struct to/from JSON. AFAIK only Vibe.d supports that well.

**Comment by wilzbach** [comment]
I think we have got a clear consensus here, so it just depends on @s-ludwig agreeing to this too and doing the transfer.

**Comment by s-ludwig** [comment]
Transferred now: https://github.com/dlang-community/std_data_json

**Comment by jacob-carlborg** [comment]
> One thing that std_data_json (and std.json) are lacking is the ability to go from/to a struct to/from JSON. AFAIK only Vibe.d supports that well.

Isn’t that more suitable for a sterilization library, which could also support other formats like XML and YAML?

**Comment by Geod24** [comment]
> Isn’t that more suitable for a sterilization library, which could also support other formats like XML and YAML?

That's an interesting typo :)

I think you have more experience in this domain than I do, but here's my thoughts:
- How much is gained by splitting this in its own library ? Is the reflection code really that heavy ?
- This is one of those things which needs to "just work" IMO.
- How much code needs to be format-specific ?

I expected the answer to the first point to be "not much" TBH.

**Comment by WebFreak001** [comment]
imo I don't think inlcuding a generic serialization library doesn't make a lot of sense as many formats have different ways to represent lots of different scenarios.

JSON for example is really simple as it's just key/value with possible struct values. XML on the other hand supports things like attributes, the order matters, namespaces, comments, etc. Comments in XML or YAML could for example also be wanted to be serialized.

Specific (de)serializers could of course also be optimized for faster reading as far as the format allows skipping through it and other possibly format specific optimizations.

Of course a generic serialization library could include a lot of good usability perks making (de)serializing easy, predictable and customizable, but then they become quite heavy, which would of course make much more sense in a separate library.

What does make sense though is a generic library for listing all the properties (both simple values and property methods, but also static/enum values if needed) that should get serialized like [painlesstraits](https://code.dlang.org/packages/painlesstraits).

I like vibe.d's (de)serialization functionality, but it's not perfect. If you want to change a global serialization policy like skipping default values in serialization you will have to write custom serialization functions for each struct you want to serialize (or mixin them into every struct) and because of its generic nature it's not the most memory efficient.

**Comment by jacob-carlborg** [comment]
> That's an interesting typo :)

Stupid auto correct :).

> How much is gained by splitting this in its own library ? Is the reflection code really that heavy ?

No, but I expect other features can be added that would not otherwise be part of `std.data.json`.

> This is one of those things which needs to "just work" IMO.

Definitely.

Just a thought.

Other reasons would be:

* Separation of concern
* Uniform interface to output a struct/class using different formats, i.e.
    ```d
    struct Foo { int a, int b }
    Foo.init.serialize!(Format.Json);
    Foo.init.serialize!(Format.Yaml);
    ```
