### ISSUE TITLE
request adoption of https://code.dlang.org/packages/money

### ISSUE THREAD

**Issue by mw66** [dlang-community/discussions#44]
I found this package is simple but efficient, however it looks like it's no longer maintained by its original owner.  @qznc

There are issues found 

https://github.com/qznc/d-money/issues

esp. this bug:

https://github.com/qznc/d-money/issues/11

It's small package, with a relative large user base:

https://code.dlang.org/packages/money
Download Stats:
6 downloads today
122 downloads this week
966 downloads this month
9300 downloads total

I think it worth to be adopted.

**Comment by mw66** [comment]
https://forum.dlang.org/post/lqyiddgwkbaqzsdelnox@forum.dlang.org

On Friday, 22 May 2020 at 22:54:30 UTC, Seb wrote:
> , but I agree that it 
> currently has too little presence (and maintainers). We 
> generally only move a package if there's a volunteer in dlang 
> community that actually is interested in maintaining the 
> library (though it's not hard to become such a volunteer).

I can take one of the issue I found.  And @m3m0ry has express interest in take over the other one.

Just let me know the setup steps (any link somewhere?) on how to adopt the project to dlang-community, and someone who can do code review for me.

**Comment by mw66** [comment]
@wilzbach  FYI

**Comment by qznc** [comment]
Sorry for neglecting it. I now changed my notification settings to get emails from Github again.

Anyways, I'm probably not the fastest one to respond. Maybe we can share the maintainer-ship?

**Comment by mw66** [comment]
@qznc  I think it's better to have a team (in the community) to maintain it, since any individual may fail to respond (e.g. on vacation, or other personal reasons).

I hope you can support my suggestion here in this thread:

https://forum.dlang.org/thread/wpzlnvmidmvkfrrockik@forum.dlang.org

more concretely: it's better to move the repo under "dlang-community".  You and me can both sign up as maintainers. More importantly we have a team behind, if we both are busy.

**Comment by wilzbach** [comment]
Sorry for the late reply.

> You and me can both sign up as maintainers. More importantly we have a team behind, if we both are busy.

That's great to hear, though to set expectations right please don't expect anything super fancy from being in the dlang-community organization (we're all just volunteers). It just means that (1) it's a lot easier to add collaborator without loosing the dub package and (2) chances are higher that there's someone with merge rights who can merge trivial PRs when the package is broken due to a new DMD versions. Lastly, (3) it's a lot easier to add packages from dlang-community to Buildkite and thus avoid them ever being broken again as many DMD maintainers now automatically have access to the package in case e.g. deprecations have been ignored or a critical fix is required.

@qznc I sent out an invite to the dlang-community organization (might be useful in either case). Anyhow, if you interested in moving and more permissions are required to move the project, please let me know. We can either make you admin or you temporarily transfer the project to an admin.

@mingwugmail I also sent out an invite to the dlang-community org to you. We're glad to have you here ;-)

**Comment by qznc** [comment]
Here we are: https://github.com/dlang-community/d-money

Dub is also adapted. The CI stuff is not setup yet.
