### ISSUE TITLE
Hacktoberfest contributions

### ISSUE THREAD

**Issue by ljmf00** [dlang-community/discussions#48]
Hi @dlang-community,

CC: @wilzbach

In this month, is runnning an event called [Hacktoberfest](https://hacktoberfest.digitalocean.com/) which is sponsored by DigitalOcean and the objective is to bring new contributors to open source projects like this. During this month, if you are interested participating, would be cool to add `hacktoberfest` topic to every relevant repositories.

If you have any trouble adding the topic, see the event details here https://hacktoberfest.digitalocean.com/details#maintainers or github documentation for adding the topic here https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests .

Thanks and happy Hacktoberfest,

**Comment by wilzbach** [comment]
Thanks a lot for the ping and idea!

However, in my experience Hackoktoberfest is just a promotion event and a few students "participate" by making 3 pull requests to a readme to get the free shirt, so I'm not super keen on getting involved in this marketing event - especially as most of the repositories here lack maintainers that could review actual work/improvements.
It might be more interesting for phobos and dmd, but we have tried it twice there before and only got a few fake PRs.

Anyhow, I generally like the idea of making it easier for people to enter a new community and prepping material for them, but dlang-community is a bit different as most projects here are in maintenance only mode and the organization was created so that critical fixes can be merged at upstream without creating a new dub package.

**Comment by ljmf00** [comment]
> Thanks a lot for the ping and idea!

:smiley: 

> However, in my experience Hackoktoberfest is just a promotion event and a few students "participate" by making 3 pull requests to a readme to get the free shirt, so I'm not super keen on getting involved in this marketing event - especially as most of the repositories here lack maintainers that could review actual work/improvements.

I thought it could be very interesting for some people.

> It might be more interesting for phobos and dmd, but we have tried it twice there before and only got a few fake PRs.

Oh yeah, I totally understand that. I didn't know that fake PRs were that aggressive. In fact, I didn't know that dlang already did that.

> Anyhow, I generally like the idea of making it easier for people to enter a new community and prepping material for them, but dlang-community is a bit different as most projects here are in maintenance only mode and the organization was created so that critical fixes can be merged at upstream without creating a new dub package.

Ok. Thanks for the reply anyway.

**Comment by wilzbach** [comment]
>  I didn't know that fake PRs were that aggressive. In fact, I didn't know that dlang already did that.

e.g. https://github.com/dlang/dmd/pull/8796

**Comment by ljmf00** [comment]
Yup, that's pretty sad :disappointed: . I totally understand the decision because it's really annoying dealing with this. That said, I'm going to close this thread.
